# Generated by Django 2.2.3 on 2019-08-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190804_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Date_de_naissance',
            field=models.DateField(blank=True, verbose_name='Puchase(mm/dd/yy)'),
        ),
    ]
