# Generated by Django 2.2.3 on 2019-08-09 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190804_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Adresse',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='lieu_Naissance',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
